languageCode = "en-us"
title = "MTC Powder Solutions"
theme = "mtc"

[pagination]
  pagerSize = 12

[permalinks]
  categories = "/:slug/"
  pages = ":sections[1:]/:slug/" # include every folder except the first one aka "pages"

# Write stats to json (for purge CSS)
[build]
  writeStats = true

# External menu links
[[menu.main]]
  name = "HIP Services"
  url = "https://hip.mtcpowdersolutions.com/"
  weight = 99

[[menu.footer]]
  name = "HIP Services"
  url = "https://hip.mtcpowdersolutions.com/"